apiVersion: v1
kind: PersistentVolume
metadata:
  name: discord-data-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/discord-data"
